### ISSUE TITLE
[Feature Request]: Hide the extension fullscreen button

### ISSUE THREAD

**Issue by kutawhat** [daksh2k/Spicetify-stuff#107]
### Choose the extension for feature request.
Full Screen Mode

### 📝 Provide a description of the new feature
It's nice to have an option to hide Spotify's default full screen button, but I'd like to hide an extension full screen button.

Thanks for your awesome work btw!

### ➕ Additional Information
No response

**Comment by daksh2k** [comment]
You can also customize the extensions activation methods, in settings. Otherwise, if it's for another extension, you can just choose to just remove it or ask the extension dev.

<img width="590" alt="Screenshot 2023-08-21 at 3 33 13 PM" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/e6122d0e-6dae-4e14-bda8-d8cfb686b06b">
