### ISSUE TITLE
[Bug]: playNext causing queue issue

### ISSUE THREAD

**Issue by SoNotMC** [daksh2k/Spicetify-stuff#124]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Play Next

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.25.1011.g0348b2ea
Spicetify v2.27.2
Theme: Comfy / SoNot (custom color profile for theme)
Extensions: QueueTime.js, seekonscroll.js, songstats.js, fullAlbumDate.js, spotifyGenres.js, find-duplicates.js, beautiful-lyrics.js, lastfm.js, volumePercentageWrapper.js, theme.js
Custom apps: marketplace
```

### 📝 Description

Adding to queue no longer works while having the playNext extension enabled.
Also when playing a playlist shuffled or not it will not play anymore songs apart from the one I click on.

When removing playNext everything returns to normal operation.

### 📸 Screenshots

Here is a breif video showing what it does. [sonot.pics/view/Ry8K6M.mp4](https://sonot.pics/view/Ry8K6M.mp4)

**Comment by SIMULATAN** [comment]
I personally noticed that when using "Play next", rather than playing the desired track after the current one, spotify breaks and shows a default cover. Skipping to the next song doesn't do anything, showing the queue just shows one empty element in the queue and that's all. To fix it, I have to play some playlist or track, after which sometimes the queue fixes itself and the next track is the added one.
Is that what you're describing or am I facing a separate issue?

**Comment by SoNotMC** [comment]
Yeh pretty much but mine wouldn't fix until I remove the addon, glad its not just me 😂

**Comment by daksh2k** [comment]
Should be fixed now I think, although I couldn't reproduce the issue on my end, changed the queue insertion logic from #116

**Comment by daksh2k** [comment]
Sure, that’d be great!

**Comment by SoNotMC** [comment]
Seems to have an issue of even showing the button now while having it enabled. I have rebooted my client completely. However, my queue is currently working.
