### ISSUE TITLE
[Bug]: Multiple lyrics

### ISSUE THREAD

**Issue by JxxIT** [daksh2k/Spicetify-stuff#127]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Save Playlists

### ℹ Environment / Computer Info

```Markdown
Spotify voor macOS (Apple Silicon)
1.2.26.1187.g36b715a1
Spicetify v2.28.1
Theme: Default Dynamic / Base
Extensions: section-marker.js, beautiful-lyrics.js, fullScreenWrapper.js, adblock.js, default-dynamic.js, Vibrant.min.js
Custom apps: marketplace, eternal-jukebox, lyrics-plus
```

### 📝 Description

Some songs (like Bloody Mary - TMW, BE.TH) have a option to use multiple lyrics, and it breaks the whole lyrics.

### 📸 Screenshots

<img width="1327" alt="Scherm­afbeelding 2023-12-10 om 16 20 32" src="https://github.com/daksh2k/Spicetify-stuff/assets/110342008/0afac007-5447-48f9-97ef-193febaec9c3">

**Comment by daksh2k** [comment]
That's because, lyrics are provided by another custom app [`lyrics-plus`](https://spicetify.app/docs/advanced-usage/custom-apps/#lyrics-plus), which comes bundled with spicetify. In this case synced lyrics may not be available, to only show synced lyrics go to the lyrics page and right click on synced tab. If they are not available, the lyrics won't automatically show that. 

<img width="515" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/f285b176-6a2c-43b5-93f1-de81c462c9d8">
