### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Artseee** [daksh2k/Spicetify-stuff#141]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Support for resizing and moving the lyrics and the song name and cover on screen.

**Comment by daksh2k** [comment]
Not in the scope of the extension, the whole UI would break if components are allowed to move around randomly.
As for resizing lyrics font can be resized, otherwise song name and cover are dynamically sized based on available space.
<img width="253" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/77efc6ba-e8e5-4844-aef0-1a7bf6fe9c88">
