### ISSUE TITLE
FullScreen.js doesn't work

### ISSUE THREAD

**Issue by frodo36** [daksh2k/Spicetify-stuff#2]
Just installed fullScreen.js and it doesn't seem to do anything.

spotify version: 1.1.73
spicetify version: 2.8.3

console error log:
![image](https://user-images.githubusercontent.com/88240067/145637691-ca6c550a-e6fb-4ec5-850b-e40c02a89141.png)

**Comment by daksh2k** [comment]
I see 2 errors related to that extension, the reference error shouldn't disrupt anything, will fix that soon, thanks for letting me know.

The TypeError I cannot reproduce, but I think it is caused by config not loading successfully you can try removing config item by running this in the console `localStorage.removeItem("full-screen-config")` then reload the client. Let me know if that works!

**Comment by frodo36** [comment]
In what console should I put that? I tried PowerShell but it shows an error. Sorry if this is kind of a noob question, but as I said, I have 0 experience with this stuff

**Comment by daksh2k** [comment]
Np, in the spotify console the one you attached the screenshot for!

**Comment by frodo36** [comment]
Thanks a LOT! It worked! And DAMN, it looks AMAZING!

**Comment by frodo36** [comment]
One more thing, anytime I open fullScreenmode, it starts in Tv mode. Is there any way of making it start in defaukt mode?

**Comment by daksh2k** [comment]
There should 2 buttons if you press tv button on topbar it will open with tv mode, if you open with fullscreen button from bottom left it will open with the default one.

I will also change the icons in future to differentiate from original spotify.

**Comment by frodo36** [comment]
![image](https://user-images.githubusercontent.com/88240067/145671285-e79f2403-0875-49e5-a72c-30705a3431a7.png)
for me theres only one button

**Comment by daksh2k** [comment]
The other one should be on bottom right with fullscreen icon.

**Comment by frodo36** [comment]
Oooooooohhhhhh- Thanks-
Is there a way of removing the default spotify fullscreen?

**Comment by daksh2k** [comment]
You can remove that button by looking through the devtools and getting the selector of that button and use `display: none;` property to hide it.
[this](https://developer.chrome.com/docs/devtools/dom/) and [this](https://www.w3schools.com/cssref/pr_class_display.asp) can help you get started.
If you are interested I would recommend [learning](https://www.freecodecamp.org/learn) a little HTML and CSS so that you can customize spotify how you like it. 
Cheers!

**Comment by frodo36** [comment]
Thanks!
