### ISSUE TITLE
[Feature Request]: Center align lyrics to the right half side of the screen

### ISSUE THREAD

**Issue by Changedit** [daksh2k/Spicetify-stuff#21]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Hi there, just realised the lyrics-plus integrated lyrics display at the right side of the screen and it alignt to the right side of the window/monitor/display, I think it would look better if we have the ability to make the lyrics be centered within the right half side of the window just like how the song info+controls are centered at the left half side of the window in default mode.

**Comment by daksh2k** [comment]
It's already there, you can open settings by right clicking on empty area and manage this setting and many more! :)

**Comment by Changedit** [comment]
Hi there, I have already looked at the options pages, it seems there is only alignment settings for the text itself and not the whole lyrics+ display alignment relative to the right half side of the window.

**Comment by daksh2k** [comment]
There is only text in the lyrics, so that can be aligned, it would help if you could elaborate more on what you mean ideally with pictures.

Check this image lyrics are aligned to the center relative to the right side of the window.
![image](https://user-images.githubusercontent.com/42179185/189728796-a2998270-256b-4342-b689-3631608711e3.png)

Settings which can be changed for lyrics.

![image](https://user-images.githubusercontent.com/42179185/189728900-2c5605d1-74a8-49ae-99b7-7098c6522f65.png)

**Comment by TheRealDenzon** [comment]
When the lyrics are in a lower font size they fix themselves to the edge of the screen like the image provided shows. The only solution I have to this is to make the font bigger.
![image](https://user-images.githubusercontent.com/69125747/200434175-f5d74fc3-58f5-4037-8eae-1864e3d708dc.png)

**Comment by daksh2k** [comment]
Should be fixed in `v2.2.0`
