### ISSUE TITLE
[Feature Request]: Auto Fullscreen Mode

### ISSUE THREAD

**Issue by vos6434** [daksh2k/Spicetify-stuff#25]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Make Spotify go into Fullscreen Mode when starting the app. This would be useful when using a Steam Deck as it is a simpled UI.

**Comment by daksh2k** [comment]
Valid feature request and easy to implement, but there will be some limitations due to automatic launching.

**The mode cannot be launched in fullscreen because requesting fullscreen requires a user gesture like a button click or key press. So if it is automatically launched the spotify window won't be in fullscreen.**

I was thinking about adding options regarding this:
1. Auto launch in last used mode
2. Default mode
3. TV Mode

**Comment by daksh2k** [comment]
Added in `v2.0.0`.
