### ISSUE TITLE
Percentage doesnt show anymore

### ISSUE THREAD

**Issue by R1see** [daksh2k/Spicetify-stuff#4]
I guess the title says it I have percentage installed it used to show the percentage but it doesnt anymore .

**Comment by daksh2k** [comment]
It has already been fixed in [this commit](https://github.com/daksh2k/Spicetify-stuff/commit/97e5d28010cd8454ee2f22e4d837c80dab261609).
Update the extension manually.
Or if you have installed from Spicetify Marketplace it should have already been updated, if not force update by opening devtools and  <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>

**Comment by daksh2k** [comment]
@R1see  does it work as intended?
If so I'll be closing this issue.

**Comment by R1see** [comment]
It suddenly showed up today ty :)
