### ISSUE TITLE
add tap to seek feature for fullScreen.js

### ISSUE THREAD

**Issue by SupLiCatinG** [daksh2k/Spicetify-stuff#5]
Lyrics-plus have this feature but i can't use tap lyrics to seek feature with fullScreen.js

**Comment by daksh2k** [comment]
Are you talking about the double clicking to seek shortcut?
If so that may not work inside the extension as the dblclick shortcut is used as a way to exit.

I'll see for adding logic for ignoring the double clicks inside the lyrics container.

Till then you can comment this [line](https://github.com/daksh2k/Spicetify-stuff/blob/394098440e6aceae970957f4c5b63e2d27a24a7a/Extensions/fullScreen.js#L2261) in  the code.

Otherwise the lyrics inside the extension depend on the lyrics-plus custom app to work, so the functionality should be same for both.

**Comment by SupLiCatinG** [comment]
Lyrics-plus behaving normally, yeah maybe ignoring double clicks in lyrics container fix this problem.
