### ISSUE TITLE
[Feature Request]:   support for Spotify Canvas available on mobile devices.

### ISSUE THREAD

**Issue by newBonfire** [daksh2k/Spicetify-stuff#66]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

It'd be really awesome to see the spotify canvas feature on desktop too. there is an [extension](https://github.com/itsmeow/Spicetify-Canvas/issues) already doing this, but I can't get it to work. Perhaps an integration to that extension would be great.

I also have an idea of youtube video playing in background synced with spotify (with sponsorblock support etc), but I think that would require a lot work.

**Comment by daksh2k** [comment]
This is because Canvas uses mp4 video format which is not supported by the Spotify desktop app, so you have to through all the hoops mentioned in the extensions README in the Spotify app to get it working. 

And for the video one check the comment on this https://github.com/daksh2k/Spicetify-stuff/issues/62

Unfortunately, there is no easier workaround that I know of. So this will be out of the scope of this extension, feel free to add a comment if you meant something else, I am closing the issue currently.

**Comment by ameliorability** [comment]
Now that Canvas is added to the desktop app, I feel that an integration would be sick :eyes:
