### ISSUE TITLE
[Play Next]: Move track to top of the queue in queue page

### ISSUE THREAD

**Issue by Tetrax-10** [daksh2k/Spicetify-stuff#70]
### Choose the extension for feature request.

Play Next

### 📝 Provide a description of the new feature

Thx for this beautiful extension 💖. I use it in day to day basis. It would be nice to able to move the tracks to the top of the queue that is present in "Next in queue" section when on queue page.

Rough code :

```js
if( Spicetify.Platform.History.location.pathname === "/queue" && isTrackInUsersQueue ) {
    const tracks = popSelectedTracksFromQueue()
    pushTracksToTop(tracks)
}
```

### ➕ Additional Information

![image](https://github.com/daksh2k/Spicetify-stuff/assets/75513645/a2e568e1-69fa-4fde-8747-645ae01e6fce)

**Comment by Tetrax-10** [comment]
Adding the tracks to the top works but i want it to move the track to the top if the track is already present in the user's queue instead of just adding it to the top as it causes duplicate tracks.

**Comment by daksh2k** [comment]
The behaviour is adding stuff, this extension doesn't allow reordering stuff, that's a separate use case. It will create a lot of confusion if I add it as a separate option. So this will be currently out of scope, feel free to add a separate comment if you meant something else. I am closing the issue now.
BTW why not just drag stuff in the queue if you want to reorder stuff, as that's much faster rather than selecting, right-clicking and selecting play next if you just want to reorder?

**Comment by Tetrax-10** [comment]
I use sort by playcount to add songs to queue. where sometimes I want to move some songs to the top of the queue ( play as next song ) so though this extension can extend this feature as this extension allows song to play next.
