### ISSUE TITLE
[Feature Request/Question]:  Disable Album Artwork

### ISSUE THREAD

**Issue by plopin3472** [daksh2k/Spicetify-stuff#72]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Hey, don't know if there's an option to this, I've tried doing so within the available settings, but the artwork still appears at fullscreen. Am I missing something? If not, then it'll be pretty cool to see added.

### ➕ Additional Information

An option called ''Disable Album Artwork'' which basically hides that, but only shows the background colors, or whatever the user has choosen to be displayed.

**Comment by daksh2k** [comment]
Hi @plopin3472, I tried what you said but the UI will look a little weird without the foreground artwork, there is one mode called the TV Mode which is minimal and has a small artwork, and you can mess with the background to your heart's extent.

If you still want to hide the artwork you do so using CSS styling, you can remove that image by looking through the devtools and getting the selector of that artwork and using the `display: none;` property to hide it.

[this](https://developer.chrome.com/docs/devtools/dom/) and [this](https://www.w3schools.com/cssref/pr_class_display.asp) can help you get started.
If you are interested I would recommend [learning](https://www.freecodecamp.org/learn) a little HTML and CSS so that you can customize and style Spotify how you like it. 
Cheers!
