### ISSUE TITLE
Center lyrics for fullScreen.js?

### ISSUE THREAD

**Issue by insideric** [daksh2k/Spicetify-stuff#9]
Maybe I look too much into things but the lyrics in full screen aren't centered but are just below the center. It would be nice to know if there was a way to make the lyrics be in the center (if there already is one). 
![image](https://user-images.githubusercontent.com/86028964/155276076-6097627c-1a24-45be-a93e-68643e6513f0.png)
Otherwise, great extension!

**Comment by daksh2k** [comment]
Actually the lyrics are provided by the `lyrics-plus` custom app which comes bundled with spicetify. So this extension just uses that to display lyrics.

If you want more detailed lyrics settings, you can manage that in it's [settings](https://spicetify.app/docs/getting-started/custom-apps#lyrics-plus).
 
Now I assume you are talking about vertical alignment as horizontal alignment seems good,  it's caused by I think this setting in  `lyrics-plus`. 
![image](https://user-images.githubusercontent.com/42179185/155311203-5d8aaf76-ca59-487f-be36-649ce89526fe.png)

If it's `0` it causes this issue, for a workaround you can try messing with this [value](https://github.com/daksh2k/Spicetify-stuff/blob/master/Extensions/fullScreen.js#L355) in the extension to align it manually.

**Comment by insideric** [comment]
Ahh I see. I changed the lines to show before and changed it manually and it's better now. Thank you so much!

**Comment by fluffy-git** [comment]
> If you want more detailed lyrics [settings](https://spicetify.app/docs/getting-started/custom-apps#lyrics-plus), you can manage that in it's settings.

the link seems to not exist anymore ...
can anyone explain what i have to do so i can center the lyrics horizontally?

**Comment by daksh2k** [comment]
@fluffy-git 
That is just the description about `lyrics-plus` custom app, it provides many settings, like choosing lyrics-provider, managing how many lines you want to show. You can play around with them, to customise how you like it.

This is the updated link https://spicetify.app/docs/advanced-usage/custom-apps#lyrics-plus
